name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build and Release
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Debug - List files
        run: |
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          dir
          echo "cmd directory:"
          dir cmd
          echo "cmd/jv directory:"
          dir cmd\jv

      - name: Build Windows executable
        run: |
          go mod download
          go build -ldflags="-s -w" -o jv.exe .\cmd\jv\main.go

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: jv.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
