name: Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags (v1.0.0, v1.1.0, etc.)

permissions:
  contents: write

jobs:
  build:
    name: Build and Release
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build Windows executable
        run: go build -ldflags="-s -w" -o jv.exe ./cmd/jv
        env:
          CGO_ENABLED: 0
          GOOS: windows
          GOARCH: amd64

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: jv.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
